create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
create table comments (id bigint not null auto_increment, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (id)) engine=InnoDB;
create table comments_aud (id bigint not null, rev integer not null, revtype tinyint, comment_date datetime(6), poster_name varchar(255), value varchar(255), ticket_id bigint, primary key (rev, id)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table taskify_users (id bigint not null auto_increment, user_name varchar(20), user_password varchar(255), primary key (id)) engine=InnoDB;
create table tickets (id bigint not null auto_increment, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (id)) engine=InnoDB;
create table tickets_aud (id bigint not null, rev integer not null, revtype tinyint, closed_at datetime(6), ticket_description varchar(250), posted_at datetime(6), priority varchar(255), status varchar(255), ticket_title varchar(75), ticket_type varchar(255), assignee_id bigint, poster_id bigint, primary key (rev, id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles varchar(255)) engine=InnoDB;
alter table if exists comments add constraint FKj7vc0aigr2m5mew52v7ddt4fo foreign key (ticket_id) references tickets (id);
alter table if exists comments_aud add constraint FKprr41p1i93lyk0qha4ab9lfdb foreign key (rev) references revinfo (rev);
alter table if exists tickets add constraint FKr0x4d175qhwwei3w9fotkvfve foreign key (assignee_id) references taskify_users (id);
alter table if exists tickets add constraint FK54wshdbmt5uho6l6wm7nbwxqe foreign key (poster_id) references taskify_users (id);
alter table if exists tickets_aud add constraint FK1tdd5eyb1d15825plba3jmw8h foreign key (rev) references revinfo (rev);
alter table if exists user_roles add constraint FK3ne88tyibu1e83snehjgiqnc4 foreign key (user_id) references taskify_users (id);
